version: "3.9"

services:
  db:
    container_name: db
    image: postgres:14-alpine3.16
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5436:5432"
    networks:
      - db-network

  graphql-engine:
    container_name: graphql-engine
    image: hasura/graphql-engine:v2.10.2.ubuntu
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@db/fast-template
      PG_DATABASE_URL: postgres://postgres:postgres@db/fast-template
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
    networks:
      - db-network

  api:
    build: .
    container_name: api
    command: sh -c "python fastapi_template/main.py"
    environment:
      - PATH=/directory/bin:$PATH
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
